
const $=id=>document.getElementById(id), socket=io(); let myId=null,room=null,myVote=null,keys={},joy={x:0,z:0},lookActive=false,lookLast=null,yaw=0,pitch=-.18,lastSend=0,spectateTarget=null,audioCtx=null;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,900), renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x334466,1.15)); const sun=new THREE.DirectionalLight(0xffffff,1.1); sun.position.set(20,45,18); scene.add(sun);
const mats={floor:new THREE.MeshStandardMaterial({color:0x11182f,roughness:.85}),grid:new THREE.LineBasicMaterial({color:0x334155,transparent:true,opacity:.45}),dark:new THREE.MeshStandardMaterial({color:0x101830}),wood:new THREE.MeshStandardMaterial({color:0x8b5a2b}),accent:new THREE.MeshStandardMaterial({color:0x22d3ee}),red:new THREE.MeshStandardMaterial({color:0xfb7185}),green:new THREE.MeshStandardMaterial({color:0x22c55e}),yellow:new THREE.MeshStandardMaterial({color:0xf59e0b}),white:new THREE.MeshStandardMaterial({color:0xe2e8f0}),rust:new THREE.MeshStandardMaterial({color:0x7c2d12})};
const WORLD=236; const floor=new THREE.Mesh(new THREE.PlaneGeometry(WORLD,WORLD,64,64),mats.floor); floor.rotation.x=-Math.PI/2; scene.add(floor); const grid=new THREE.GridHelper(WORLD,118,0x475569,0x334155); grid.position.y=.02; scene.add(grid);
let staticObjects=[],morphables=[],objects=new Map(),designs=[]; const raycaster=new THREE.Raycaster(); function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.82,metalness:.04})} function box(w,h,d,m=mats.accent){let x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.position.y=h/2;return x} function cyl(r,h,m=mats.accent,seg=20){let x=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),m);x.position.y=h/2;return x} function sphere(r,m=mats.accent){let x=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),m);x.position.y=r;return x}
function add(g,x,y,z,s=1,ry=0){g.position.set(x,y,z);g.scale.setScalar(s);g.rotation.y+=ry;scene.add(g);staticObjects.push(g);if(g.userData&&g.userData.morphable)morphables.push(g);return g} function group(...a){let g=new THREE.Group();a.forEach(o=>g.add(o));return g}
function seed(s){let h=2166136261;for(let ch of s)h=(h^ch.charCodeAt(0))*16777619;return()=>{h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return((h>>>0)%10000)/10000}}
function label(text){let c=document.createElement('canvas');c.width=256;c.height=64;let ctx=c.getContext('2d');ctx.fillStyle='rgba(0,0,0,.68)';ctx.roundRect(8,8,240,48,14);ctx.fill();ctx.font='900 25px system-ui';ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText(text,128,42);let spr=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));spr.scale.set(5,1.25,1);spr.position.y=3;return spr}
function makeProp(type,team='prop',me=false){let m=team==='hunter'?mats.red:(team==='spectator'?mats.white:mats.accent), g=new THREE.Group();
 if(type==='Hunter'){g.add(cyl(.55,1.7,mats.red,18));g.add(sphere(.48,mats.red));g.children[1].position.y=2.05;g.add(box(.25,.9,.25,mats.dark));g.children[2].position.set(.55,1.1,.25)}
 else if(['Barrel','Can','Bottle','Cup','Mug','Bucket','TrashCan','Pipe'].includes(type)){g.add(cyl(type==='Pipe'?.32:.58,type==='Bottle'?1.65:1.2,m,18));if(type==='Bottle')g.add(cyl(.25,.45,mats.white,16));}
 else if(['Ball','Rock','Bush','Snowman'].includes(type)){g.add(sphere(type==='Ball'? .72: .82, type==='Bush'?mats.green:m)); if(type==='Snowman'){let s=sphere(.52,mats.white);s.position.y=1.25;g.add(s)}}
 else if(['Bench','Chair','Stool'].includes(type)){g.add(box(1.7,.25,.65,mats.wood));g.add(box(.25,.8,.25,mats.wood));g.children[1].position.set(-.55,.4,-.2);let b=box(1.7,.9,.2,mats.wood);b.position.z=.38;b.position.y=.8;g.add(b)}
 else if(['Lamp','Sign','Candle'].includes(type)){g.add(cyl(.12,1.7,mats.dark,12));let top=type==='Candle'?sphere(.25,mats.yellow):box(.9,.45,.22,mats.yellow);top.position.y=1.8;g.add(top)}
 else if(['Cabinet','Register','Monitor','Printer','Server','Cabinet','ShelfBox','Cart'].includes(type)){g.add(box(1.25,1,1,m));let t=box(.9,.18,.7,mats.dark);t.position.y=1.1;g.add(t)}
 else if(['Tire','Log','TreeStump'].includes(type)){let c=cyl(.58,.8,type==='Tire'?mats.dark:mats.wood,22);c.rotation.z=Math.PI/2;c.position.y=.58;g.add(c)}
 else {let w=1+(type.length%3)*.2,h=.75+(type.length%4)*.16,d=.9+(type.length%5)*.1;g.add(box(w,h,d,m)); if(['House','BrokenBot','Robot','ToyCar'].includes(type)){g.add(box(.45,.35,.45,mats.dark));g.children[1].position.set(.45,h+.2,.2)}}
 g.userData.propType=type; g.userData.morphable=true; if(me)g.traverse(o=>{if(o.material)o.material=o.material.clone(),o.material.opacity=.45,o.material.transparent=true});return g}
function buildDesigns(){const base=['Crate','TrashCan','Plant','Bench','Barrel','Box','Cone','Lamp','Rock','Chair','Can','Bottle','Register','SnackBox','Cart','ShelfBox','Bush','Log','TreeStump','PicnicBox','Block','Ball','Book','Cup','Pillow','ToyCar','Robot','Monitor','Cabinet','Printer','Mug','DeskBox','Server','Pallet','CandyBox','Tire','Lollipop','GumBox','Cabinet','Stool','Speaker','TokenBox','PrizeBox','NeonCube','Plate','Pan','BreadBox','Apple','Pipe','Bucket','BrokenBot','Snowman','Candle','Door','Mailbox','FencePost','Table','Couch','TV','Fridge','VendingMachine','Dumpster','Rubble','ToolBox','HayBale','Pumpkin','Gravestone','RoadCone','StreetLight','SodaMachine','ArcadeCabinet','Wardrobe','Nightstand','DishRack','SnowCrate','BrokenChair','WoodPile']; for(let i=0;i<360;i++)designs.push(base[i%base.length])} buildDesigns();
function tree(x,z,r,kind='pine'){let g=new THREE.Group();g.add(cyl(.28,2.2,mats.wood,10)); if(kind==='pine'){for(let i=0;i<3;i++){let cone=new THREE.Mesh(new THREE.ConeGeometry(1.25-i*.22,2.1,8),mats.green);cone.position.y=2.2+i*.82;g.add(cone)}}else{let crown=sphere(1.45,mats.green);crown.position.y=2.9;g.add(crown)}g.userData={propType:'Tree',morphable:false};add(g,x,0,z,1+r()*.25,r()*6.28)}
function house(x,z,theme,r){let g=new THREE.Group();let w=10+r()*6,d=9+r()*5,h=4.2;let wallMat=theme==='haunted'?mats.rust:theme==='snow'?mats.white:mats.wood;let back=box(w,h,.42,wallMat);back.position.z=-d/2;g.add(back);let left=box(.42,h,d,wallMat);left.position.x=-w/2;g.add(left);let right=box(.42,h,d,wallMat);right.position.x=w/2;g.add(right);let frontL=box(w*.34,h,.42,wallMat);frontL.position.set(-w*.33,0,d/2);g.add(frontL);let frontR=box(w*.34,h,.42,wallMat);frontR.position.set(w*.33,0,d/2);g.add(frontR);let floor2=box(w,.25,d,mats.dark);floor2.position.y=.05;g.add(floor2);let roof=box(w+1.5,1.2,d+1.5,theme==='abandoned'?mats.dark:mats.red);roof.position.y=h+.7;g.add(roof);let door=box(1.8,2.5,.18,mats.dark);door.position.set(0,1.25,d/2+.35);g.add(door);for(let ix of [-.3,.3]){let win=box(1.1,.9,.16,mats.yellow);win.position.set(ix*w,2.55,d/2+.42);g.add(win)}for(let i=0;i<3;i++){let furniture=makeProp(['Chair','Table','Cabinet','Couch','Lamp'][i%5]);furniture.position.set((r()-.5)*w*.65,0,(r()-.5)*d*.55);furniture.scale.setScalar(.9);g.add(furniture)}g.userData={propType:'House',morphable:false};add(g,x,0,z,1,r()*6.28)}
function clutter(map,count,r){for(let i=0;i<count;i++){let t=designs[(i+map.id.length*13)%designs.length];add(makeProp(t), (r()-.5)*220,0,(r()-.5)*220,.75+r()*.8,r()*6.28)}}
function shelves(x,z,len,rot=0){let g=new THREE.Group();for(let i=0;i<4;i++){let s=box(len,.22,1.1,mats.dark);s.position.y=.65+i*.72;g.add(s)}for(let i=-1;i<=1;i+=2){let p=box(.2,3.1,.25,mats.accent);p.position.set(i*len/2,1.55,.45);g.add(p)}add(g,x,0,z,1,rot)}
function rebuild(map){staticObjects.forEach(o=>scene.remove(o));staticObjects=[];morphables=[];floor.material.color.set(new THREE.Color(map.color).offsetHSL(0,-.45,-.38));scene.background=new THREE.Color(map.time==='Night'?'#020617':map.time==='Sunset'?'#371a20':map.color).offsetHSL(0,-.45,-.18);let wall=mat(new THREE.Color(map.color).offsetHSL(0,-.25,-.25));[[0,2,-120,240,4,1],[0,2,120,240,4,1],[-120,2,0,1,4,240],[120,2,0,1,4,240]].forEach(w=>add(box(w[3],w[4],w[5],wall),w[0],w[1],w[2]));let r=seed(map.id);
 if(['suburb','snow','haunted'].includes(map.style)){for(let i=0;i<36;i++)house((i%6)*35-88,Math.floor(i/6)*35-88,map.style,r);for(let i=0;i<90;i++)tree((r()-.5)*224,(r()-.5)*224,r,map.style==='snow'?'pine':'oak');for(let i=0;i<42;i++)add(box(6,.35,22,mats.dark),(r()-.5)*220,0,(r()-.5)*220,1,r()*6.28)}
 if(map.style==='abandoned'||map.style==='junkyard'){for(let i=0;i<20;i++){add(box(3+r()*7,2+r()*4,.7+r()*2,mats.rust),(r()-.5)*216,0,(r()-.5)*216,1,r()*6.28)}for(let i=0;i<18;i++)add(makeProp(['Tire','Pipe','Barrel','Pallet','BrokenBot'][i%5]),(r()-.5)*218,0,(r()-.5)*218,1+r()*.7,r()*6.28)}
 if(map.style==='market'||map.style==='warehouse'||map.style==='arcade'){for(let i=0;i<18;i++)shelves((i%6)*18-45,Math.floor(i/6)*20-16,8+r()*4,(i%2)*Math.PI/2);}
 if(map.style==='park'){for(let i=0;i<36;i++)add(makeProp(i%3?'Bush':'Rock'),(r()-.5)*220,0,(r()-.5)*220,1+r()*1.2);for(let i=0;i<10;i++)add(makeProp('Bench'),(r()-.5)*212,0,(r()-.5)*212,1.2,r()*6.28)}
 if(map.style==='office'){for(let i=0;i<28;i++){add(box(5,1.2,3,mats.wood),(i%7)*16-48,0,Math.floor(i/7)*20-30,1,r()*0.2);add(makeProp(i%2?'Monitor':'Chair'),(i%7)*16-48,0,Math.floor(i/7)*20-30,1)}}
 if(map.style==='bedroom'||map.style==='kitchen'){for(let i=0;i<16;i++)add(box(6+r()*8,1+r()*2,4+r()*6,i%2?mats.wood:mats.dark),(r()-.5)*214,0,(r()-.5)*214,1,r()*6.28)}
 clutter(map,430,r);}
function upsert(p){let rec=objects.get(p.id);if(!rec||rec.type!==p.propType||rec.team!==p.team){if(rec)scene.remove(rec.g);let g=makeProp(p.propType,p.team,p.id===myId);g.add(label((p.bot?'🤖 ':'')+p.name));scene.add(g);rec={g,type:p.propType,team:p.team};objects.set(p.id,rec)}rec.g.position.lerp(new THREE.Vector3(p.x,p.y,p.z),p.id===myId?1:.38);rec.g.rotation.y=p.ry||0;rec.g.visible=!(p.id===myId&&p.team!=='spectator')}
function renderUI(){if(!room)return;let me=room.players[myId];$('roomInfo').textContent=`Room: ${room.code} • ${room.map.name}`;$('phase').textContent=`${room.phase.toUpperCase()} • ${room.timeLeft}s • Round ${room.round}/${room.maxRounds}`;$('role').textContent=`Role: ${me?.team||'waiting'} ${me?.team==='prop'?'• '+me.propType:''}`;$('soundLine').innerHTML=room.phase==='round'&&me?.team==='prop'?`You will whistle in <span class="sound">${room.soundCountdown}s</span>`:'';$('score').innerHTML=Object.values(room.players).map(p=>`<span class="tag"><i class="dot ${p.team}"></i>${p.bot?'🤖 ':''}${p.name} · ${p.team} · ${p.score}</span>`).join('');let showMsg=room.msg&&!/made noise|Sound event/i.test(room.msg);$('events').style.display=showMsg?'block':'none';$('events').textContent=showMsg?room.msg:'';$('vote').style.display=room.phase==='voting'?'block':'none';$('home').style.display=room?'block':'none';$('spectate').style.display=me?.team==='spectator'?'block':'none';$('start').style.display=room.hostId===myId?'block':'none';let humans=Object.values(room.players).filter(p=>!p.bot).length,votes=Object.keys(room.votes||{}).filter(id=>!room.players[id]?.bot).length;$('voteStatus').textContent=`${votes}/${humans} players voted • Home does not need votes`;$('maps').innerHTML=room.maps.map(m=>{let c=Object.values(room.votes||{}).filter(v=>v===m.id).length;return `<button class="mapBtn ${myVote===m.id?'active':''}" data-map="${m.id}" style="box-shadow:inset 0 -6px 0 ${m.color}"><span class="mapName">${m.name}</span><span class="votes">${m.time} • ${m.style} • ${c} vote${c===1?'':'s'}</span></button>`}).join('');document.querySelectorAll('.mapBtn').forEach(b=>b.onclick=()=>{myVote=b.dataset.map;socket.emit('voteMap',{mapId:myVote});renderUI()}); if($('morphAim')) $('morphAim').style.display=me?.team==='prop'?'block':'none'; if(me?.team==='prop'){$('propbar').style.display='flex';$('propbar').innerHTML='<span class="tag">Aim at a real object in the map, then tap MORPH. No fake prop list.</span>'}else $('propbar').style.display='none';$('tagBtn').style.display=me?.team==='hunter'?'block':'none';$('hint').style.display=(room.phase==='hide'||me?.team==='spectator')?'block':'none';$('hint').textContent=me?.team==='spectator'?'Caught — spectating. Tap Spectate to switch camera.':(me?.team==='hunter'?`Hunter locked for ${room.timeLeft}s`:`Hide now. Transform without respawning.`)}
function needName(){let n=$('name').value.trim();if(!n){$('err').textContent='Pick a username first.';$('name').focus();return null}return n}
$('create').onclick=()=>{let n=needName();if(n)socket.emit('createRoom',{name:n})};$('join').onclick=()=>{let n=needName();if(n)socket.emit('joinRoom',{name:n,roomCode:$('code').value})};$('start').onclick=()=>socket.emit('forceStart');$('home').onclick=$('homeVote').onclick=()=>socket.emit('leaveRoom');$('spectate').onclick=()=>socket.emit('spectateNext');$('tagBtn').onclick=()=>{let me=room?.players[myId];if(!me)return;let best=null,bd=99;for(let p of Object.values(room.players)){if(p.team==='prop'){let d=Math.hypot(me.x-p.x,me.z-p.z);if(d<bd){bd=d;best=p}}} if(best&&bd<3.6)socket.emit('tag',{targetId:best.id});else toast('No hider close enough')};
socket.on('joined',d=>{myId=d.id;$('menu').style.display='none';$('err').textContent=''});socket.on('leftRoom',()=>{room=null;myId=null;objects.forEach(o=>scene.remove(o.g));objects.clear();$('menu').style.display='grid';$('home').style.display='none'});socket.on('errorMsg',m=>$('err').textContent=m);socket.on('notice',m=>toast(m));socket.on('propSound',d=>{whistle();toast('🔊 WHISTLE: '+d.message)});socket.on('state',st=>{let old=room?.mapId;room=st;if(old!==room.mapId)rebuild(room.map);let live=new Set(Object.keys(room.players));for(let id of [...objects.keys()])if(!live.has(id)){scene.remove(objects.get(id).g);objects.delete(id)}Object.values(room.players).forEach(upsert);renderUI()});
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)(); if(audioCtx.state==='suspended')audioCtx.resume()}
function whistle(){ensureAudio();let t=audioCtx.currentTime,g=audioCtx.createGain();g.gain.setValueAtTime(1,t);g.gain.exponentialRampToValueAtTime(.001,t+1.05);g.connect(audioCtx.destination);[880,1320,1760].forEach((hz,i)=>{let o=audioCtx.createOscillator();o.type='sine';o.frequency.setValueAtTime(hz,t+i*.06);o.frequency.exponentialRampToValueAtTime(hz*1.25,t+.65+i*.04);o.connect(g);o.start(t+i*.04);o.stop(t+1.05)})}
['pointerdown','touchstart','click'].forEach(ev=>addEventListener(ev,ensureAudio,{once:true,passive:true}));

function aimedProp(){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);let hits=raycaster.intersectObjects(morphables,true);if(!hits.length)return null;let o=hits[0].object;while(o&&!o.userData?.propType)o=o.parent;return o?.userData?.propType||null}
function morphAimed(){let me=room?.players?.[myId];if(!me||me.team!=='prop')return toast('Only hiders can morph.');let type=aimedProp();if(!type)return toast('Aim at a real prop first.');socket.emit('changeProp',{propType:type});toast('Morphed into '+type+' in place');}
setInterval(()=>{let me=room?.players?.[myId];let b=$('morphAim');if(!b)return;if(me?.team==='prop'){let type=aimedProp();b.textContent=type?'MORPH: '+type:'AIM AT PROP';}},350);

function toast(m){$('toast').textContent=m;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',2600)}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);renderer.domElement.addEventListener('pointerdown',e=>{if(e.clientX<innerWidth*.45)return;lookActive=true;lookLast={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture?.(e.pointerId);});addEventListener('pointerup',()=>{lookActive=false;lookLast=null});addEventListener('pointermove',e=>{if(!lookActive||!lookLast)return;let dx=e.clientX-lookLast.x,dy=e.clientY-lookLast.y;yaw-=dx*.0065;pitch=Math.max(-.95,Math.min(.95,pitch+dy*.0048));lookLast={x:e.clientX,y:e.clientY}});
const joyEl=$('joystick'),knob=$('knob');let ja=false,jc=null;joyEl.addEventListener('pointerdown',e=>{ja=true;jc={x:e.clientX,y:e.clientY};joyEl.setPointerCapture(e.pointerId)});joyEl.addEventListener('pointermove',e=>{if(!ja)return;let dx=e.clientX-jc.x,dy=e.clientY-jc.y,len=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);joy.x=Math.cos(a)*len/42;joy.z=Math.sin(a)*len/42;knob.style.left=38+Math.cos(a)*len+'px';knob.style.top=38+Math.sin(a)*len+'px'});function resetJoy(){ja=false;joy={x:0,z:0};knob.style.left='38px';knob.style.top='38px'} joyEl.addEventListener('pointerup',resetJoy);joyEl.addEventListener('pointercancel',resetJoy);joyEl.addEventListener('lostpointercapture',resetJoy);
function frame(t){requestAnimationFrame(frame);let me=room?.players?.[myId],camP=me;if(me?.team==='spectator'&&me.spectating&&room.players[me.spectating])camP=room.players[me.spectating]; if(me){let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.z,r=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x;let mag=Math.hypot(f,r);if(mag>1){f/=mag;r/=mag}if(me.team!=='spectator'&&!(me.team==='hunter'&&room.phase==='hide')&&mag>.03){let sp=me.team==='hunter'?.52:.42,fw=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),rt=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));let nx=me.x+fw.x*f*sp+rt.x*r*sp,nz=me.z+fw.z*f*sp+rt.z*r*sp;me.x=Math.max(-118,Math.min(118,nx));me.z=Math.max(-118,Math.min(118,nz));me.ry=yaw;if(t-lastSend>33){socket.emit('move',{x:me.x,z:me.z,ry:yaw});lastSend=t}} if(camP){let dist=camP.team==='hunter'?10.5:12.5,baseH=camP.team==='hunter'?5.2:5.9;let lookY=camP.y+1.4-pitch*11;let target=new THREE.Vector3(camP.x+Math.sin(yaw)*8,lookY,camP.z+Math.cos(yaw)*8);let pos=new THREE.Vector3(camP.x-Math.sin(yaw)*dist,camP.y+baseH,camP.z-Math.cos(yaw)*dist);camera.position.lerp(pos,.22);camera.lookAt(target)}}renderer.render(scene,camera)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});rebuild({id:'lobby',style:'suburb',color:'#7c3aed',time:'Day',props:['Box']});
