
const $=id=>document.getElementById(id), socket=io(); let myId=null,room=null,myVote=null,keys={},joy={x:0,z:0},swipe={f:0,r:0},yaw=0,pitch=-.18,lastSend=0,spectateTarget=null;
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,900), renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); document.body.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x334466,1.15)); const sun=new THREE.DirectionalLight(0xffffff,1.1); sun.position.set(20,45,18); scene.add(sun);
const mats={floor:new THREE.MeshStandardMaterial({color:0x11182f,roughness:.85}),grid:new THREE.LineBasicMaterial({color:0x334155,transparent:true,opacity:.45}),dark:new THREE.MeshStandardMaterial({color:0x101830}),wood:new THREE.MeshStandardMaterial({color:0x8b5a2b}),accent:new THREE.MeshStandardMaterial({color:0x22d3ee}),red:new THREE.MeshStandardMaterial({color:0xfb7185}),green:new THREE.MeshStandardMaterial({color:0x22c55e}),yellow:new THREE.MeshStandardMaterial({color:0xf59e0b}),white:new THREE.MeshStandardMaterial({color:0xe2e8f0}),rust:new THREE.MeshStandardMaterial({color:0x7c2d12})};
const floor=new THREE.Mesh(new THREE.PlaneGeometry(128,128,32,32),mats.floor); floor.rotation.x=-Math.PI/2; scene.add(floor); const grid=new THREE.GridHelper(128,64,0x475569,0x334155); grid.position.y=.02; scene.add(grid);
let staticObjects=[],objects=new Map(),designs=[]; function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.82,metalness:.04})} function box(w,h,d,m=mats.accent){let x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.position.y=h/2;return x} function cyl(r,h,m=mats.accent,seg=20){let x=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),m);x.position.y=h/2;return x} function sphere(r,m=mats.accent){let x=new THREE.Mesh(new THREE.SphereGeometry(r,20,14),m);x.position.y=r;return x}
function add(g,x,y,z,s=1,ry=0){g.position.set(x,y,z);g.scale.setScalar(s);g.rotation.y+=ry;scene.add(g);staticObjects.push(g);return g} function group(...a){let g=new THREE.Group();a.forEach(o=>g.add(o));return g}
function seed(s){let h=2166136261;for(let ch of s)h=(h^ch.charCodeAt(0))*16777619;return()=>{h+=h<<13;h^=h>>>7;h+=h<<3;h^=h>>>17;h+=h<<5;return((h>>>0)%10000)/10000}}
function label(text){let c=document.createElement('canvas');c.width=256;c.height=64;let ctx=c.getContext('2d');ctx.fillStyle='rgba(0,0,0,.68)';ctx.roundRect(8,8,240,48,14);ctx.fill();ctx.font='900 25px system-ui';ctx.textAlign='center';ctx.fillStyle='white';ctx.fillText(text,128,42);let spr=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true}));spr.scale.set(5,1.25,1);spr.position.y=3;return spr}
function makeProp(type,team='prop',me=false){let m=team==='hunter'?mats.red:(team==='spectator'?mats.white:mats.accent), g=new THREE.Group();
 if(type==='Hunter'){g.add(cyl(.55,1.7,mats.red,18));g.add(sphere(.48,mats.red));g.children[1].position.y=2.05;g.add(box(.25,.9,.25,mats.dark));g.children[2].position.set(.55,1.1,.25)}
 else if(['Barrel','Can','Bottle','Cup','Mug','Bucket','TrashCan','Pipe'].includes(type)){g.add(cyl(type==='Pipe'?.32:.58,type==='Bottle'?1.65:1.2,m,18));if(type==='Bottle')g.add(cyl(.25,.45,mats.white,16));}
 else if(['Ball','Rock','Bush','Snowman'].includes(type)){g.add(sphere(type==='Ball'? .72: .82, type==='Bush'?mats.green:m)); if(type==='Snowman'){let s=sphere(.52,mats.white);s.position.y=1.25;g.add(s)}}
 else if(['Bench','Chair','Stool'].includes(type)){g.add(box(1.7,.25,.65,mats.wood));g.add(box(.25,.8,.25,mats.wood));g.children[1].position.set(-.55,.4,-.2);let b=box(1.7,.9,.2,mats.wood);b.position.z=.38;b.position.y=.8;g.add(b)}
 else if(['Lamp','Sign','Candle'].includes(type)){g.add(cyl(.12,1.7,mats.dark,12));let top=type==='Candle'?sphere(.25,mats.yellow):box(.9,.45,.22,mats.yellow);top.position.y=1.8;g.add(top)}
 else if(['Cabinet','Register','Monitor','Printer','Server','Cabinet','ShelfBox','Cart'].includes(type)){g.add(box(1.25,1,1,m));let t=box(.9,.18,.7,mats.dark);t.position.y=1.1;g.add(t)}
 else if(['Tire','Log','TreeStump'].includes(type)){let c=cyl(.58,.8,type==='Tire'?mats.dark:mats.wood,22);c.rotation.z=Math.PI/2;c.position.y=.58;g.add(c)}
 else {let w=1+(type.length%3)*.2,h=.75+(type.length%4)*.16,d=.9+(type.length%5)*.1;g.add(box(w,h,d,m)); if(['House','BrokenBot','Robot','ToyCar'].includes(type)){g.add(box(.45,.35,.45,mats.dark));g.children[1].position.set(.45,h+.2,.2)}}
 if(me)g.traverse(o=>{if(o.material)o.material=o.material.clone(),o.material.opacity=.45,o.material.transparent=true});return g}
function buildDesigns(){const base=['Crate','TrashCan','Plant','Bench','Barrel','Box','Cone','Lamp','Rock','Chair','Can','Bottle','Register','SnackBox','Cart','ShelfBox','Bush','Log','TreeStump','PicnicBox','Block','Ball','Book','Cup','Pillow','ToyCar','Robot','Monitor','Cabinet','Printer','Mug','DeskBox','Server','Pallet','CandyBox','Tire','Lollipop','GumBox','Cabinet','Stool','Speaker','TokenBox','PrizeBox','NeonCube','Plate','Pan','BreadBox','Apple','Pipe','Bucket','BrokenBot','Snowman','Candle']; for(let i=0;i<240;i++)designs.push(base[i%base.length])} buildDesigns();
function house(x,z,theme,r){let g=new THREE.Group();let body=box(7+r()*4,3.2,6+r()*3,theme==='haunted'?mats.rust:theme==='snow'?mats.white:mats.wood);g.add(body);let roof=box(body.geometry.parameters.width+1,1.1,body.geometry.parameters.depth+1,theme==='abandoned'?mats.dark:mats.red);roof.position.y=3.75;g.add(roof);for(let i=-1;i<=1;i+=2){let w=box(.9,.8,.1,mats.yellow);w.position.set(i*2,1.8,body.geometry.parameters.depth/2+.07);g.add(w)}add(g,x,0,z,1,r()*6.28)}
function clutter(map,count,r){for(let i=0;i<count;i++){let t=designs[(i+map.id.length*13)%designs.length];add(makeProp(t), (r()-.5)*112,0,(r()-.5)*112,.75+r()*.8,r()*6.28)}}
function shelves(x,z,len,rot=0){let g=new THREE.Group();for(let i=0;i<4;i++){let s=box(len,.22,1.1,mats.dark);s.position.y=.65+i*.72;g.add(s)}for(let i=-1;i<=1;i+=2){let p=box(.2,3.1,.25,mats.accent);p.position.set(i*len/2,1.55,.45);g.add(p)}add(g,x,0,z,1,rot)}
function rebuild(map){staticObjects.forEach(o=>scene.remove(o));staticObjects=[];floor.material.color.set(new THREE.Color(map.color).offsetHSL(0,-.45,-.38));scene.background=new THREE.Color(map.time==='Night'?'#020617':map.time==='Sunset'?'#371a20':map.color).offsetHSL(0,-.45,-.18);let wall=mat(new THREE.Color(map.color).offsetHSL(0,-.25,-.25));[[0,2,-64,128,4,1],[0,2,64,128,4,1],[-64,2,0,1,4,128],[64,2,0,1,4,128]].forEach(w=>add(box(w[3],w[4],w[5],wall),w[0],w[1],w[2]));let r=seed(map.id);
 if(['suburb','snow','haunted'].includes(map.style)){for(let i=0;i<14;i++)house((i%5)*23-46,Math.floor(i/5)*25-20,map.style,r);for(let i=0;i<11;i++)add(box(6,.35,18,mats.dark),(r()-.5)*104,0,(r()-.5)*104,1,r()*6.28)}
 if(map.style==='abandoned'||map.style==='junkyard'){for(let i=0;i<20;i++){add(box(3+r()*7,2+r()*4,.7+r()*2,mats.rust),(r()-.5)*106,0,(r()-.5)*106,1,r()*6.28)}for(let i=0;i<18;i++)add(makeProp(['Tire','Pipe','Barrel','Pallet','BrokenBot'][i%5]),(r()-.5)*108,0,(r()-.5)*108,1+r()*.7,r()*6.28)}
 if(map.style==='market'||map.style==='warehouse'||map.style==='arcade'){for(let i=0;i<18;i++)shelves((i%6)*18-45,Math.floor(i/6)*20-16,8+r()*4,(i%2)*Math.PI/2);}
 if(map.style==='park'){for(let i=0;i<36;i++)add(makeProp(i%3?'Bush':'Rock'),(r()-.5)*112,0,(r()-.5)*112,1+r()*1.2);for(let i=0;i<10;i++)add(makeProp('Bench'),(r()-.5)*102,0,(r()-.5)*102,1.2,r()*6.28)}
 if(map.style==='office'){for(let i=0;i<28;i++){add(box(5,1.2,3,mats.wood),(i%7)*16-48,0,Math.floor(i/7)*20-30,1,r()*0.2);add(makeProp(i%2?'Monitor':'Chair'),(i%7)*16-48,0,Math.floor(i/7)*20-30,1)}}
 if(map.style==='bedroom'||map.style==='kitchen'){for(let i=0;i<16;i++)add(box(6+r()*8,1+r()*2,4+r()*6,i%2?mats.wood:mats.dark),(r()-.5)*104,0,(r()-.5)*104,1,r()*6.28)}
 clutter(map,210,r);}
function upsert(p){let rec=objects.get(p.id);if(!rec||rec.type!==p.propType||rec.team!==p.team){if(rec)scene.remove(rec.g);let g=makeProp(p.propType,p.team,p.id===myId);g.add(label((p.bot?'🤖 ':'')+p.name));scene.add(g);rec={g,type:p.propType,team:p.team};objects.set(p.id,rec)}rec.g.position.lerp(new THREE.Vector3(p.x,p.y,p.z),p.id===myId?1:.38);rec.g.rotation.y=p.ry||0;rec.g.visible=!(p.id===myId&&p.team!=='spectator')}
function renderUI(){if(!room)return;let me=room.players[myId];$('roomInfo').textContent=`Room: ${room.code} • ${room.map.name}`;$('phase').textContent=`${room.phase.toUpperCase()} • ${room.timeLeft}s • Round ${room.round}/${room.maxRounds}`;$('role').textContent=`Role: ${me?.team||'waiting'} ${me?.team==='prop'?'• '+me.propType:''}`;$('soundLine').innerHTML=room.phase==='round'?`🔊 prop sound in <span class="sound">${room.soundCountdown}s</span>`:'';$('score').innerHTML=Object.values(room.players).map(p=>`<span class="tag"><i class="dot ${p.team}"></i>${p.bot?'🤖 ':''}${p.name} · ${p.team} · ${p.score}</span>`).join('');$('events').style.display=room.msg?'block':'none';$('events').textContent=room.msg;$('vote').style.display=room.phase==='voting'?'block':'none';$('home').style.display=room?'block':'none';$('spectate').style.display=me?.team==='spectator'?'block':'none';$('start').style.display=room.hostId===myId?'block':'none';let humans=Object.values(room.players).filter(p=>!p.bot).length,votes=Object.keys(room.votes||{}).filter(id=>!room.players[id]?.bot).length;$('voteStatus').textContent=`${votes}/${humans} players voted • Home does not need votes`;$('maps').innerHTML=room.maps.map(m=>{let c=Object.values(room.votes||{}).filter(v=>v===m.id).length;return `<button class="mapBtn ${myVote===m.id?'active':''}" data-map="${m.id}" style="box-shadow:inset 0 -6px 0 ${m.color}"><span class="mapName">${m.name}</span><span class="votes">${m.time} • ${m.style} • ${c} vote${c===1?'':'s'}</span></button>`}).join('');document.querySelectorAll('.mapBtn').forEach(b=>b.onclick=()=>{myVote=b.dataset.map;socket.emit('voteMap',{mapId:myVote});renderUI()}); if(me?.team==='prop'){$('propbar').style.display='flex';$('propbar').innerHTML=room.map.props.map(p=>`<button class="propBtn ${me.propType===p?'active':''}" data-prop="${p}">${p}</button>`).join('');document.querySelectorAll('.propBtn').forEach(b=>b.onclick=()=>socket.emit('changeProp',{propType:b.dataset.prop}))}else $('propbar').style.display='none';$('tagBtn').style.display=me?.team==='hunter'?'block':'none';$('hint').style.display=(room.phase==='hide'||me?.team==='spectator')?'block':'none';$('hint').textContent=me?.team==='spectator'?'Caught — spectating. Tap Spectate to switch camera.':(me?.team==='hunter'?`Hunter locked for ${room.timeLeft}s`:`Hide now. Transform without respawning.`)}
function needName(){let n=$('name').value.trim();if(!n){$('err').textContent='Pick a username first.';$('name').focus();return null}return n}
$('create').onclick=()=>{let n=needName();if(n)socket.emit('createRoom',{name:n})};$('join').onclick=()=>{let n=needName();if(n)socket.emit('joinRoom',{name:n,roomCode:$('code').value})};$('start').onclick=()=>socket.emit('forceStart');$('home').onclick=$('homeVote').onclick=()=>socket.emit('leaveRoom');$('spectate').onclick=()=>socket.emit('spectateNext');$('tagBtn').onclick=()=>{let me=room?.players[myId];if(!me)return;let best=null,bd=99;for(let p of Object.values(room.players)){if(p.team==='prop'){let d=Math.hypot(me.x-p.x,me.z-p.z);if(d<bd){bd=d;best=p}}} if(best&&bd<3.6)socket.emit('tag',{targetId:best.id});else toast('No hider close enough')};
socket.on('joined',d=>{myId=d.id;$('menu').style.display='none';$('err').textContent=''});socket.on('leftRoom',()=>{room=null;myId=null;objects.forEach(o=>scene.remove(o.g));objects.clear();$('menu').style.display='grid';$('home').style.display='none'});socket.on('errorMsg',m=>$('err').textContent=m);socket.on('notice',m=>toast(m));socket.on('propSound',d=>toast('🔊 '+d.message));socket.on('state',st=>{let old=room?.mapId;room=st;if(old!==room.mapId)rebuild(room.map);let live=new Set(Object.keys(room.players));for(let id of [...objects.keys()])if(!live.has(id)){scene.remove(objects.get(id).g);objects.delete(id)}Object.values(room.players).forEach(upsert);renderUI()});
function toast(m){$('toast').textContent=m;$('toast').style.display='block';clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').style.display='none',2600)}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let down=false,last=null;renderer.domElement.addEventListener('pointerdown',e=>{down=true;last={x:e.clientX,y:e.clientY}});addEventListener('pointerup',()=>{down=false;last=null;swipe={f:0,r:0}});addEventListener('pointermove',e=>{if(!down||!last)return;let dx=e.clientX-last.x,dy=e.clientY-last.y;yaw-=dx*.006;pitch=Math.max(-.9,Math.min(.28,pitch-dy*.002));swipe.f=Math.max(-1,Math.min(1,-dy/80));swipe.r=Math.max(-.55,Math.min(.55,dx/100));last={x:e.clientX,y:e.clientY}});
const joyEl=$('joystick'),knob=$('knob');let ja=false,jc=null;joyEl.addEventListener('pointerdown',e=>{ja=true;jc={x:e.clientX,y:e.clientY};joyEl.setPointerCapture(e.pointerId)});joyEl.addEventListener('pointermove',e=>{if(!ja)return;let dx=e.clientX-jc.x,dy=e.clientY-jc.y,len=Math.min(42,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);joy.x=Math.cos(a)*len/42;joy.z=Math.sin(a)*len/42;knob.style.left=38+Math.cos(a)*len+'px';knob.style.top=38+Math.sin(a)*len+'px'});joyEl.addEventListener('pointerup',()=>{ja=false;joy={x:0,z:0};knob.style.left='38px';knob.style.top='38px'});
function frame(t){requestAnimationFrame(frame);let me=room?.players?.[myId],camP=me;if(me?.team==='spectator'&&me.spectating&&room.players[me.spectating])camP=room.players[me.spectating]; if(me){let f=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0)-joy.z+swipe.f,r=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x+swipe.r*.25;f=Math.max(-1,Math.min(1,f));r=Math.max(-1,Math.min(1,r));if(me.team!=='spectator'&&!(me.team==='hunter'&&room.phase==='hide')&&(Math.abs(f)+Math.abs(r)>0)){let sp=me.team==='hunter'?.32:.25,fw=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw)),rt=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));me.x=Math.max(-58,Math.min(58,me.x+fw.x*f*sp+rt.x*r*sp));me.z=Math.max(-58,Math.min(58,me.z+fw.z*f*sp+rt.z*r*sp));me.ry=yaw;if(t-lastSend>45){socket.emit('move',{x:me.x,z:me.z,ry:yaw});lastSend=t}} if(camP){let dist=camP.team==='hunter'?10:12.8,hi=camP.team==='hunter'?5.8:6.8,target=new THREE.Vector3(camP.x,camP.y+1,camP.z),pos=new THREE.Vector3(camP.x-Math.sin(yaw)*dist,camP.y+hi+pitch*3,camP.z-Math.cos(yaw)*dist);camera.position.lerp(pos,.16);camera.lookAt(target)}}renderer.render(scene,camera)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});rebuild({id:'lobby',style:'suburb',color:'#7c3aed',time:'Day',props:['Box']});
