const express=require('express'), http=require('http'), path=require('path');
const {Server}=require('socket.io');
const app=express(), server=http.createServer(app), io=new Server(server,{cors:{origin:'*'}});
const PORT=process.env.PORT||3000;
app.use(express.static(__dirname)); app.get('/',(_,res)=>res.sendFile(path.join(__dirname,'index.html')));
const VOTE=35,HIDE=25,ROUND=170,BETWEEN=10,MAX_ROUNDS=3,LIMIT=210,BOTS=8,SOUND_EVERY=7;
const PROPS=['Crate','Barrel','TrashCan','Bench','PicnicTable','Bush','PineTree','OakTree','Stump','Rock','Mailbox','Fence','StreetLight','TrafficLight','StopSign','Cone','Hydrant','Dumpster','Pallet','Tire','OilDrum','Pipe','Generator','ToolBox','Ladder','Wheelbarrow','CementMixer','ShippingContainer','WoodBox','Bookshelf','Chair','Table','CoffeeTable','Sofa','Armchair','Lamp','Plant','TV','Monitor','Desk','Cabinet','FileCabinet','Printer','Mug','Box','Fridge','Stove','Sink','Toilet','Bed','Nightstand','Wardrobe','Rug','HayBale','Corn','Tractor','WaterTank','Pumpkin','Tombstone','Candle','Cauldron','Snowman','SnowCrate','Arcade','VendingMachine','SodaMachine','Register','Shelf','ShoppingCart','HospitalBed','SchoolDesk','Locker','Car','Van','Truck','Ambulance','Forklift','Sandbag','Cactus','PalmTree','Log','BridgePost','Crystal','SciFiCrate','ServerRack'];
const MAPS=[
 {id:'suburb',name:'Suburban Neighborhood',style:'suburb',time:'Day',color:'#62c7ff',props:['Crate','TrashCan','Bench','Bush','PineTree','OakTree','Stump','Rock','Mailbox','Fence','StreetLight','StopSign','Cone','Hydrant','Dumpster','WoodBox','Sofa','Lamp','Plant','TV','Fridge','Bed','Wardrobe','Car','Van']},
 {id:'mansion',name:'Modern Mansion',style:'mansion',time:'Evening',color:'#38bdf8',props:['Sofa','Armchair','Table','CoffeeTable','Lamp','Plant','TV','Monitor','Desk','Cabinet','Fridge','Bed','Nightstand','Wardrobe','Rug','Bench','Bush','StreetLight','Car','Van','Crate','Box']},
 {id:'farm',name:'Farm & Barn',style:'farm',time:'Day',color:'#22c55e',props:['HayBale','Corn','Tractor','WaterTank','Barrel','WoodBox','Pallet','Crate','Fence','Mailbox','Bench','Bush','OakTree','Stump','Rock','Log','Tire','Pumpkin','Wheelbarrow']},
 {id:'cabin',name:'Forest Cabin',style:'forest',time:'Night',color:'#16a34a',props:['PineTree','OakTree','Bush','Stump','Rock','Log','Bench','PicnicTable','Barrel','Crate','Fence','Lamp','Mailbox','WoodBox','BridgePost','Tire','Box','Candle']},
 {id:'desert',name:'Desert Town',style:'desert',time:'Sunset',color:'#f59e0b',props:['Cactus','Sandbag','Barrel','Crate','WoodBox','Bench','StopSign','Cone','StreetLight','Dumpster','Pallet','Tire','OilDrum','Pipe','Mailbox','Truck','Car','Rock']},
 {id:'snow',name:'Snowy Village',style:'snow',time:'Dawn',color:'#93c5fd',props:['Snowman','SnowCrate','PineTree','Bench','StreetLight','Mailbox','Fence','Crate','Barrel','WoodBox','Rock','Log','Car','Van','Lamp','Chair','Table']},
 {id:'industrial',name:'Industrial Complex',style:'industrial',time:'Night',color:'#64748b',props:['ShippingContainer','Barrel','OilDrum','Pipe','Generator','ToolBox','Ladder','Forklift','Pallet','Tire','Dumpster','Crate','Cone','RoadBlock','Truck','Van','ServerRack','Fence','StreetLight']},
 {id:'mall',name:'Shopping Mall',style:'mall',time:'Day',color:'#ec4899',props:['Shelf','Register','ShoppingCart','VendingMachine','SodaMachine','TrashCan','Bench','Plant','Table','Chair','Box','Crate','Lamp','TV','Arcade','StreetLight','Dumpster']},
 {id:'school',name:'School Campus',style:'school',time:'Day',color:'#f97316',props:['SchoolDesk','Locker','Bench','TrashCan','Bookshelf','Chair','Table','Plant','TV','Monitor','Printer','Cabinet','Cone','StopSign','StreetLight','Bus','Crate','Box']},
 {id:'hospital',name:'Hospital Block',style:'hospital',time:'Day',color:'#06b6d4',props:['HospitalBed','Cabinet','Desk','Chair','Table','Lamp','Plant','TrashCan','Sofa','VendingMachine','Ambulance','Crate','Box','StreetLight','Bench','Monitor']},
 {id:'island',name:'Tropical Island',style:'island',time:'Day',color:'#14b8a6',props:['PalmTree','Rock','Bush','Log','Crate','Barrel','Bench','PicnicTable','BridgePost','WoodBox','Cactus','Stump','TrashCan']},
 {id:'swamp',name:'Swamp Village',style:'swamp',time:'Night',color:'#475569',props:['OakTree','Stump','Log','Rock','Bush','Crate','Barrel','BridgePost','Fence','Candle','Cauldron','WoodBox','Bench']},
 {id:'ruined',name:'Ruined City',style:'ruined',time:'Sunset',color:'#78716c',props:['Rubble','Dumpster','Pallet','Barrel','Crate','Pipe','Tire','Cone','StreetLight','StopSign','Car','Van','Rock','WoodBox','Fence','ToolBox']},
 {id:'castle',name:'Castle Courtyard',style:'castle',time:'Night',color:'#7c3aed',props:['Tombstone','Candle','Cauldron','Crate','Barrel','Bench','Rock','Fence','StreetLight','Bush','WoodBox','Bookshelf','Chair','Table']},
 {id:'caves',name:'Underground Caves',style:'cave',time:'Night',color:'#a16207',props:['Crystal','Rock','Barrel','Crate','WoodBox','Pallet','Lantern','Pipe','Stump','Log','ToolBox','Tire']},
 {id:'space',name:'Space Station',style:'space',time:'Night',color:'#0ea5e9',props:['SciFiCrate','ServerRack','Monitor','Desk','Chair','Cabinet','VendingMachine','Crate','Box','Pipe','Generator','Lamp','TrashCan']}
];
const rooms=new Map();
const clean=s=>String(s||'').replace(/[<>]/g,'').trim().slice(0,16)||'Player';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(+n)?+n:0));
function rid(){const s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='';for(let i=0;i<5;i++)c+=s[Math.random()*s.length|0];return rooms.has(c)?rid():c}
const mapOf=r=>MAPS.find(m=>m.id===r.mapId)||MAPS[0]; const humans=r=>Object.keys(r.players).filter(id=>!r.players[id].bot);
function spawn(team){let a=Math.random()*Math.PI*2, d=team==='hunter'?170:80+Math.random()*80; return {x:Math.cos(a)*d,y:1.1,z:Math.sin(a)*d,ry:Math.random()*6.28}}
function makeRoom(code,host){return {code,hostId:host,players:{},votes:{},phase:'voting',timeLeft:VOTE,round:0,mapId:MAPS[0].id,caught:{},nextSound:SOUND_EVERY,sounds:[],msg:'Vote for a map. If multiple maps tie, the wheel picks fairly.',lastHunter:null,wheel:null,matchDone:false}}
function addBots(r){const names=['MangoBot','SneakBot','SeekBot','ZippyBot','NovaBot','PixelBot','OrbitBot','WaffleBot']; for(let i=0;i<BOTS;i++){let id='bot_'+r.code+'_'+i;if(!r.players[id])r.players[id]={id,name:names[i],bot:true,team:'waiting',propType:'Player',score:0,target:null,think:0,...spawn('prop')}}}
function state(r){let ps={}; for(let [id,p] of Object.entries(r.players))ps[id]={id,name:p.name||'Player',bot:!!p.bot,team:p.team,propType:p.propType,x:p.x,y:p.y,z:p.z,ry:p.ry,score:p.score||0,caught:!!r.caught[id],spectating:p.spectating||null}; return {code:r.code,hostId:r.hostId,phase:r.phase,timeLeft:Math.ceil(r.timeLeft),round:r.round,maxRounds:MAX_ROUNDS,mapId:r.mapId,map:mapOf(r),maps:MAPS,votes:r.votes,players:ps,msg:r.msg,soundCountdown:r.phase==='round'?Math.ceil(r.nextSound):0,wheel:r.wheel,matchDone:r.matchDone}}
function emit(r){io.to(r.code).emit('state',state(r))}
function voteCounts(r){let c={}; Object.values(r.votes).forEach(v=>c[v]=(c[v]||0)+1); return c}
function chooseMap(r){let c=voteCounts(r), max=Math.max(0,...Object.values(c)); let tied=MAPS.filter(m=>(c[m.id]||0)===max); if(max===0)tied=[MAPS[Math.random()*MAPS.length|0]]; let chosen=tied[Math.random()*tied.length|0]; r.wheel=tied.length>1?{active:true,options:tied.map(x=>x.name),winner:chosen.name,until:Date.now()+2600}:null; r.mapId=chosen.id; return chosen}
function allVoted(r){let h=humans(r); return h.length && h.every(id=>r.votes[id])}
function assignRoles(r){let ids=Object.keys(r.players), h=humans(r); let pool=h.length?h:ids; if(r.lastHunter&&pool.length>1)pool=pool.filter(id=>id!==r.lastHunter); let hunter=pool[Math.random()*pool.length|0]||ids[0]; r.lastHunter=hunter; let m=mapOf(r); r.caught={}; for(let [id,p] of Object.entries(r.players)){let isH=id===hunter; p.team=isH?'hunter':'prop'; p.propType=isH?'Hunter':'Player'; p.spectating=null; p.target=null; p.think=0; Object.assign(p,spawn(p.team)); p.frozen=isH;}}
function beginRound(r){chooseMap(r); r.round++; r.phase='hide'; r.timeLeft=HIDE; r.votes={}; r.sounds=[]; r.nextSound=SOUND_EVERY; r.msg=`Round ${r.round}/${MAX_ROUNDS}: hiders have ${HIDE}s to hide and morph.`; assignRoles(r); io.to(r.code).emit('notice',r.msg); emit(r)}
function releaseHunter(r){r.phase='round'; r.timeLeft=ROUND; r.nextSound=SOUND_EVERY; r.msg='Hunter released. Listen for whistles. Props only see the whistle countdown.'; for(let p of Object.values(r.players))p.frozen=false; io.to(r.code).emit('notice','Hunter released — props will whistle every 7 seconds.'); emit(r)}
function between(r,msg){r.phase='between'; r.timeLeft=BETWEEN; r.msg=msg; io.to(r.code).emit('notice',msg); emit(r)}
function caught(r,h,t){if(!t||t.team!=='prop'||r.caught[t.id])return; r.caught[t.id]=true; t.team='spectator'; t.propType='Ghost'; t.spectating=Object.values(r.players).find(p=>p.team==='prop'&&!r.caught[p.id])?.id || h.id; h.score=(h.score||0)+1; r.msg=`${h.name} caught ${t.name}. ${t.name} is spectating until the round ends.`; io.to(r.code).emit('notice',r.msg); if(!Object.values(r.players).some(p=>p.team==='prop'&&!r.caught[p.id])) between(r,'All hiders were caught. New random hunter next round.');}
function whistle(r){let props=Object.values(r.players).filter(p=>p.team==='prop'&&!r.caught[p.id]); let payload=props.map(p=>({id:p.id,name:p.name||'Player',x:p.x,z:p.z})); r.sounds=payload; io.to(r.code).emit('propSound',{sounds:payload}); r.nextSound=SOUND_EVERY;}
function botAI(r,dt){if(!['hide','round'].includes(r.phase))return; const props=Object.values(r.players).filter(p=>p.team==='prop'&&!r.caught[p.id]); for(let p of Object.values(r.players).filter(x=>x.bot)){if(p.team==='spectator'||r.caught[p.id])continue; if(p.team==='hunter'&&r.phase==='hide')continue; p.think-=dt; if(p.think<=0){p.think=.6+Math.random()*1.2; if(p.team==='prop'){let nearest=Object.values(r.players).find(x=>x.team==='hunter'); let away=nearest?Math.atan2(p.z-nearest.z,p.x-nearest.x):Math.random()*6.28; let hide=r.phase==='hide'||Math.random()<.65; p.target={x:clamp(p.x+Math.cos(hide?away:Math.random()*6.28)*(22+Math.random()*35),-LIMIT,LIMIT), z:clamp(p.z+Math.sin(hide?away:Math.random()*6.28)*(22+Math.random()*35),-LIMIT,LIMIT)}; if(Math.random()<.24)p.propType=mapOf(r).props[Math.random()*mapOf(r).props.length|0]; } else if(p.team==='hunter'&&props.length){let target=props.reduce((a,b)=>Math.hypot(p.x-b.x,p.z-b.z)<Math.hypot(p.x-a.x,p.z-a.z)?b:a,props[0]); p.target={x:target.x+(Math.random()-.5)*8,z:target.z+(Math.random()-.5)*8}; if(Math.hypot(p.x-target.x,p.z-target.z)<5.2)caught(r,p,target); }} if(p.target){let dx=p.target.x-p.x,dz=p.target.z-p.z,d=Math.hypot(dx,dz); if(d>1){let sp=(p.team==='hunter'?18:12)*dt; p.x=clamp(p.x+dx/d*sp,-LIMIT,LIMIT); p.z=clamp(p.z+dz/d*sp,-LIMIT,LIMIT); p.ry=Math.atan2(dx,dz); }}}
}
io.on('connection',socket=>{socket.on('createRoom',({name})=>{let code=rid(), r=makeRoom(code,socket.id); rooms.set(code,r); r.players[socket.id]={id:socket.id,name:clean(name),bot:false,team:'waiting',propType:'Player',score:0,...spawn('prop')}; addBots(r); socket.join(code); socket.data.room=code; socket.emit('joined',{id:socket.id,code}); emit(r)}); socket.on('joinRoom',({name,roomCode})=>{let code=String(roomCode||'').trim().toUpperCase(),r=rooms.get(code); if(!r)return socket.emit('errorMsg','Room not found.'); r.players[socket.id]={id:socket.id,name:clean(name),bot:false,team:'waiting',propType:'Player',score:0,...spawn('prop')}; socket.join(code); socket.data.room=code; socket.emit('joined',{id:socket.id,code}); emit(r)}); socket.on('voteMap',({mapId})=>{let r=rooms.get(socket.data.room); if(!r||r.phase!=='voting')return; if(MAPS.some(m=>m.id===mapId)){r.votes[socket.id]=mapId; r.msg='Vote locked. Waiting for players or host start.'; if(allVoted(r))beginRound(r); else emit(r)}}); socket.on('forceStart',()=>{let r=rooms.get(socket.data.room); if(r&&r.hostId===socket.id&&r.phase==='voting')beginRound(r)}); socket.on('move',d=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id]; if(!p||p.team==='spectator'||(p.team==='hunter'&&r.phase==='hide'))return; p.x=clamp(d.x,-LIMIT,LIMIT); p.z=clamp(d.z,-LIMIT,LIMIT); p.ry=clamp(d.ry,-99,99);}); socket.on('changeProp',({propType})=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id]; if(!p||p.team!=='prop')return; if(mapOf(r).props.includes(propType)||PROPS.includes(propType)){p.propType=propType; p.morphed=true; emit(r)}}); socket.on('tag',({targetId})=>{let r=rooms.get(socket.data.room),h=r?.players[socket.id],t=r?.players[targetId]; if(!r||!h||h.team!=='hunter'||!t)return; if(Math.hypot(h.x-t.x,h.z-t.z)<6)caught(r,h,t); emit(r)}); socket.on('spectateNext',()=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id]; if(!p||p.team!=='spectator')return; let ids=Object.values(r.players).filter(x=>x.team==='prop'||x.team==='hunter').map(x=>x.id); if(ids.length){let i=ids.indexOf(p.spectating);p.spectating=ids[(i+1)%ids.length];emit(r)}}); socket.on('leaveRoom',()=>leave(socket)); socket.on('disconnect',()=>leave(socket));});
function leave(socket){let r=rooms.get(socket.data.room); if(!r)return; delete r.players[socket.id]; delete r.votes[socket.id]; socket.leave(r.code); socket.emit('leftRoom'); let h=humans(r); if(!h.length){rooms.delete(r.code);return} if(r.hostId===socket.id)r.hostId=h[0]; emit(r)}
setInterval(()=>{for(let r of rooms.values()){let dt=1; if(r.phase==='voting'){r.timeLeft-=dt; if(r.timeLeft<=0)beginRound(r)} else if(r.phase==='hide'){r.timeLeft-=dt; if(r.timeLeft<=0)releaseHunter(r)} else if(r.phase==='round'){r.timeLeft-=dt; r.nextSound-=dt; if(r.nextSound<=0)whistle(r); if(r.timeLeft<=0)between(r,'Props survived. New random hunter next round.')} else if(r.phase==='between'){r.timeLeft-=dt; if(r.timeLeft<=0){ if(r.round>=MAX_ROUNDS)startVoting(r); else beginRound(r)}} botAI(r,dt); emit(r)}},1000);
function startVoting(r){r.phase='voting';r.timeLeft=VOTE;r.round=0;r.votes={};r.caught={};r.wheel=null;r.matchDone=true;r.msg='3 rounds complete. Vote for the next real map or go Home.';for(let p of Object.values(r.players)){p.team='waiting';p.propType='Player';p.spectating=null;Object.assign(p,spawn('prop'))}emit(r)}
server.listen(PORT,()=>console.log('Dropz Prop Hunt running on '+PORT));
