
const express=require('express'), http=require('http'), path=require('path');
const {Server}=require('socket.io');
const app=express(), server=http.createServer(app), io=new Server(server,{cors:{origin:'*'}});
const PORT=process.env.PORT||3000;
app.use(express.static(__dirname)); app.get('/',(_,res)=>res.sendFile(path.join(__dirname,'index.html')));
const TICK=70,VOTE=35,HIDE=25,ROUND=155,BETWEEN=10,MAX_ROUNDS=3,LIMIT=58,BOTS=8,SOUND_EVERY=7;
const MAPS=[
 {id:'blockwood',name:'Blockwood Houses',style:'suburb',color:'#55c7ff',time:'Day',props:['Crate','TrashCan','Plant','Bench','Barrel','Box','Cone','Lamp','Rock','Chair'],spawnH:[0,-48],spawnP:[0,34]},
 {id:'abandoned',name:'Abandoned Factory',style:'abandoned',color:'#4b5563',time:'Night',props:['Barrel','Tire','Pallet','Crate','Pipe','Box','Bucket','Cone','BrokenBot','Rock'],spawnH:[-46,-44],spawnP:[32,36]},
 {id:'neonmarket',name:'Neon Mini Market',style:'market',color:'#06b6d4',time:'Evening',props:['Can','Bottle','Register','Crate','SnackBox','Cone','Cart','ShelfBox','TrashCan','Sign'],spawnH:[0,-48],spawnP:[25,30]},
 {id:'moonpark',name:'Moonlight Park',style:'park',color:'#22c55e',time:'Night',props:['Bush','Bench','Rock','Log','TrashCan','Lamp','Barrel','Cone','TreeStump','PicnicBox'],spawnH:[-44,38],spawnP:[34,-30]},
 {id:'toybed',name:'Toy Box Bedroom',style:'bedroom',color:'#8b5cf6',time:'Day',props:['Block','Ball','Book','Cup','Pillow','Lamp','ToyCar','Robot','Box','Chair'],spawnH:[44,-40],spawnP:[-34,35]},
 {id:'tinyoffice',name:'Tiny Office Maze',style:'office',color:'#f59e0b',time:'Day',props:['Chair','Monitor','Plant','Cabinet','Printer','Mug','DeskBox','Lamp','TrashCan','Server'],spawnH:[-46,0],spawnP:[38,0]},
 {id:'candywh',name:'Candy Warehouse',style:'warehouse',color:'#ec4899',time:'Evening',props:['Pallet','Barrel','CandyBox','Tire','Lollipop','GumBox','Crate','Cone','Cart','Box'],spawnH:[0,48],spawnP:[0,-37]},
 {id:'retroarcade',name:'Retro Arcade',style:'arcade',color:'#a855f7',time:'Night',props:['Cabinet','Stool','Speaker','TokenBox','PrizeBox','NeonCube','Sign','Crate','TrashCan','Ball'],spawnH:[45,38],spawnP:[-35,-35]},
 {id:'giantkitchen',name:'Giant Kitchen',style:'kitchen',color:'#fb7185',time:'Day',props:['Cup','Plate','Pan','Bottle','BreadBox','Apple','Mug','Box','Can','Chair'],spawnH:[-44,42],spawnP:[36,-36]},
 {id:'rustyard',name:'Rusty Junkyard',style:'junkyard',color:'#d97706',time:'Sunset',props:['Tire','Barrel','Crate','Pipe','Cone','BrokenBot','Pallet','Bucket','Rock','Sign'],spawnH:[48,0],spawnP:[-42,0]},
 {id:'snowvillage',name:'Snowy Block Village',style:'snow',color:'#93c5fd',time:'Dawn',props:['Snowman','Crate','Bench','Lamp','Box','Bush','Rock','Log','Sign','Barrel'],spawnH:[0,48],spawnP:[-34,-32]},
 {id:'haunted',name:'Haunted Block Manor',style:'haunted',color:'#7c2d12',time:'Night',props:['Chair','Book','Candle','Crate','Barrel','Plant','Lamp','Box','Cabinet','Rock'],spawnH:[-46,-46],spawnP:[34,34]}
];
const rooms=new Map();
function rid(){const s='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let c='';for(let i=0;i<5;i++)c+=s[Math.random()*s.length|0];return rooms.has(c)?rid():c}
const clean=s=>String(s||'').replace(/[<>]/g,'').trim().slice(0,16); const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number.isFinite(n)?n:0));
const mapOf=r=>MAPS.find(m=>m.id===r.mapId)||MAPS[0]; const humanIds=r=>Object.keys(r.players).filter(id=>!r.players[id].bot);
function spawn(m,team){let b=team==='hunter'?m.spawnH:m.spawnP;return {x:b[0]+(Math.random()-.5)*9,y:1.1,z:b[1]+(Math.random()-.5)*9,ry:Math.random()*6.28}}
function room(code,host){return {code,hostId:host,players:{},votes:{},phase:'voting',timeLeft:VOTE,round:0,mapId:MAPS[0].id,caught:{},sounds:[],nextSound:SOUND_EVERY,msg:'Vote for a real map. Host can start early after players vote.',lastHunters:[],matchDone:false}}
function addBots(r){let names=['MangoBot','SneakBot','SeekBot','ZippyBot','NovaBot','PixelBot','OrbitBot','WaffleBot'];for(let i=0;i<BOTS;i++){let id='bot_'+r.code+'_'+i;if(!r.players[id])r.players[id]={id,name:names[i],bot:true,team:'waiting',propType:'Player',score:0,health:3,target:null,think:0,...spawn(mapOf(r),'prop')}}}
function publicState(r){let ps={};for(let [id,p] of Object.entries(r.players))ps[id]={id,name:p.name,bot:!!p.bot,team:p.team,propType:p.propType,x:p.x,y:p.y,z:p.z,ry:p.ry,score:p.score||0,caught:!!r.caught[id],spectating:p.spectating||null};return {code:r.code,hostId:r.hostId,phase:r.phase,timeLeft:Math.ceil(r.timeLeft),round:r.round,maxRounds:MAX_ROUNDS,mapId:r.mapId,map:mapOf(r),maps:MAPS,votes:r.votes,players:ps,msg:r.msg,sounds:r.sounds.slice(-10),soundCountdown:r.phase==='round'?Math.max(0,Math.ceil(r.nextSound)):0,matchDone:r.matchDone}}
function emit(r){io.to(r.code).emit('state',publicState(r))}
function counts(r){let c={};Object.values(r.votes).forEach(v=>c[v]=(c[v]||0)+1);return c}
function votedMap(r){let c=counts(r),best=MAPS[Math.random()*MAPS.length|0].id,n=-1;for(let m of MAPS){if((c[m.id]||0)>n){n=c[m.id]||0;best=m.id}}return best}
function allHumansVoted(r){let h=humanIds(r);return h.length && h.every(id=>r.votes[id])}
function assign(r){let ids=Object.keys(r.players);let humans=humanIds(r);let pool=humans.length?humans:ids;if(r.lastHunters.length){let alt=pool.filter(x=>!r.lastHunters.includes(x));if(alt.length)pool=alt}let hunter=pool[Math.random()*pool.length|0];r.lastHunters=[hunter];let m=mapOf(r);for(let [id,p] of Object.entries(r.players)){let isH=id===hunter;p.team=isH?'hunter':'prop';p.propType=isH?'Hunter':m.props[Math.random()*m.props.length|0];p.health=isH?100:3;p.spectating=null;delete r.caught[id];Object.assign(p,spawn(m,p.team));p.frozen=isH;p.target=null}}
function startVote(r){r.phase='voting';r.timeLeft=VOTE;r.round=0;r.votes={};r.caught={};r.sounds=[];r.matchDone=false;r.msg='3-round match complete. Vote together for a new map or press Home anytime.';for(let p of Object.values(r.players)){p.team='waiting';p.propType='Player';p.spectating=null;Object.assign(p,spawn(mapOf(r),'prop'))}emit(r)}
function startRound(r){r.mapId=votedMap(r);r.round++;r.phase='hide';r.timeLeft=HIDE;r.votes={};r.sounds=[];r.nextSound=SOUND_EVERY;r.msg=`Round ${r.round}/${MAX_ROUNDS}: props hide and morph in place. Hunter unlocks soon.`;assign(r);io.to(r.code).emit('notice',r.msg);emit(r)}
function release(r){r.phase='round';r.timeLeft=ROUND;r.nextSound=SOUND_EVERY;r.msg='Hunter released. Props make noise every 7 seconds.';for(let p of Object.values(r.players))p.frozen=false;io.to(r.code).emit('notice','Hunter released — listen for prop sounds!');emit(r)}
function between(r,msg){r.phase='between';r.timeLeft=BETWEEN;r.msg=msg;io.to(r.code).emit('notice',msg);emit(r)}
function catchPlayer(r,h,t){if(!t||t.team!=='prop'||r.caught[t.id])return;r.caught[t.id]=true;t.team='spectator';t.propType='Ghost';t.spectating=Object.values(r.players).find(p=>p.team==='prop'&&!r.caught[p.id])?.id||h.id;h.score=(h.score||0)+1;r.msg=`${h.name} caught ${t.name}! ${t.name} is now spectating.`;io.to(r.code).emit('notice',r.msg);if(!Object.values(r.players).some(p=>p.team==='prop'&&!r.caught[p.id]))between(r,'All hiders were caught. Switching roles next round!')}
function propSounds(r){let props=Object.values(r.players).filter(p=>p.team==='prop'&&!r.caught[p.id]);for(let p of props)r.sounds.push({id:p.id,name:p.name,x:p.x,z:p.z,t:Date.now()});r.msg=props.length?`Sound event: ${props.map(p=>p.name).join(', ')} made noise.`:'No props left.';io.to(r.code).emit('propSound',{message:r.msg,sounds:r.sounds.slice(-props.length)});r.nextSound=SOUND_EVERY}
function botAI(r,dt){if(!['hide','round'].includes(r.phase))return;let aliveProps=Object.values(r.players).filter(p=>p.team==='prop'&&!r.caught[p.id]);for(let p of Object.values(r.players).filter(p=>p.bot)){if(p.team==='spectator'||r.caught[p.id])continue;if(p.team==='hunter'&&r.phase==='hide')continue;p.think-=dt;if(p.think<=0){p.think=.6+Math.random()*1.4;if(p.team==='prop'){let m=mapOf(r); if(Math.random()<.18)p.propType=m.props[Math.random()*m.props.length|0]; p.target={x:p.x+(Math.random()-.5)*(r.phase==='hide'?45:18),z:p.z+(Math.random()-.5)*(r.phase==='hide'?45:18)}}else if(p.team==='hunter'){let target=null,b=999;for(let s of r.sounds.slice(-14)){let d=Math.hypot(p.x-s.x,p.z-s.z);if(d<b){b=d;target={x:s.x+(Math.random()-.5)*7,z:s.z+(Math.random()-.5)*7}}}if(!target&&aliveProps.length&&Math.random()<.45){let q=aliveProps[Math.random()*aliveProps.length|0]; target={x:q.x+(Math.random()-.5)*8,z:q.z+(Math.random()-.5)*8}}if(!target)target={x:(Math.random()-.5)*LIMIT*1.8,z:(Math.random()-.5)*LIMIT*1.8};p.target=target}}
 if(p.target){let dx=p.target.x-p.x,dz=p.target.z-p.z,len=Math.hypot(dx,dz)||1,spd=(p.team==='hunter'?9.2:6.4)*dt;p.x=clamp(p.x+dx/len*spd,-LIMIT,LIMIT);p.z=clamp(p.z+dz/len*spd,-LIMIT,LIMIT);p.ry=Math.atan2(dx,dz);if(len<1.5)p.target=null} if(p.team==='hunter'&&r.phase==='round'){for(let q of aliveProps){if(Math.hypot(p.x-q.x,p.z-q.z)<2.8){catchPlayer(r,p,q);break}}}}
}
io.on('connection',socket=>{
 socket.on('createRoom',({name})=>{let n=clean(name);if(!n)return socket.emit('errorMsg','Pick a username before creating a lobby.');let c=rid(),r=room(c,socket.id);rooms.set(c,r);r.players[socket.id]={id:socket.id,name:n,team:'waiting',propType:'Player',score:0,...spawn(mapOf(r),'prop')};addBots(r);socket.join(c);socket.data.room=c;socket.emit('joined',{id:socket.id,roomCode:c});emit(r)});
 socket.on('joinRoom',({name,roomCode})=>{let n=clean(name),c=String(roomCode||'').toUpperCase().trim(),r=rooms.get(c);if(!n)return socket.emit('errorMsg','Pick a username before joining.');if(!r)return socket.emit('errorMsg','Room not found.');r.players[socket.id]={id:socket.id,name:n,team:'waiting',propType:'Player',score:0,...spawn(mapOf(r),'prop')};socket.join(c);socket.data.room=c;socket.emit('joined',{id:socket.id,roomCode:c});emit(r)});
 socket.on('voteMap',({mapId})=>{let r=rooms.get(socket.data.room);if(!r||!MAPS.some(m=>m.id===mapId))return;r.votes[socket.id]=mapId;r.msg=`${r.players[socket.id]?.name||'Player'} voted. Waiting for everyone.`;if(r.phase==='voting'&&allHumansVoted(r))r.timeLeft=Math.min(r.timeLeft,4);emit(r)});
 socket.on('forceStart',()=>{let r=rooms.get(socket.data.room);if(r&&r.hostId===socket.id&&r.phase==='voting')startRound(r)});
 socket.on('move',d=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id];if(!p||p.bot||p.team==='spectator'||(p.team==='hunter'&&r.phase==='hide'))return;p.x=clamp(+d.x,-LIMIT,LIMIT);p.z=clamp(+d.z,-LIMIT,LIMIT);p.ry=clamp(+d.ry,-99,99)});
 socket.on('changeProp',({propType})=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id];if(!r||!p||p.team!=='prop')return;let m=mapOf(r);if(m.props.includes(propType)){p.propType=propType;r.msg=`${p.name} morphed into ${propType} in place.`;emit(r)}});
 socket.on('tag',({targetId})=>{let r=rooms.get(socket.data.room),h=r?.players[socket.id],t=r?.players[targetId];if(!r||!h||h.team!=='hunter'||r.phase!=='round')return;if(t&&t.team==='prop'&&Math.hypot(h.x-t.x,h.z-t.z)<3.5)catchPlayer(r,h,t)});
 socket.on('spectateNext',()=>{let r=rooms.get(socket.data.room),p=r?.players[socket.id];if(!r||!p||p.team!=='spectator')return;let ids=Object.values(r.players).filter(q=>q.team==='prop'||q.team==='hunter').map(q=>q.id);if(ids.length){let i=ids.indexOf(p.spectating);p.spectating=ids[(i+1+ids.length)%ids.length];emit(r)}});
 socket.on('leaveRoom',()=>{let r=rooms.get(socket.data.room);if(r){delete r.players[socket.id];delete r.votes[socket.id];if(r.hostId===socket.id){let h=humanIds(r)[0];if(h)r.hostId=h}emit(r);if(!humanIds(r).length)rooms.delete(r.code)}socket.leave(socket.data.room||'');socket.data.room=null;socket.emit('leftRoom')});
 socket.on('disconnect',()=>{let r=rooms.get(socket.data.room);if(r){delete r.players[socket.id];delete r.votes[socket.id];if(r.hostId===socket.id){let h=humanIds(r)[0];if(h)r.hostId=h}if(!humanIds(r).length)rooms.delete(r.code);else emit(r)}});
});
setInterval(()=>{for(let r of rooms.values()){let dt=TICK/1000;if(r.phase==='voting'){r.timeLeft-=dt;if(r.timeLeft<=0)startRound(r)}else if(r.phase==='hide'){r.timeLeft-=dt;if(r.timeLeft<=0)release(r)}else if(r.phase==='round'){r.timeLeft-=dt;r.nextSound-=dt;if(r.nextSound<=0)propSounds(r);if(r.timeLeft<=0)between(r,'Props survived the timer. Roles rotate next round.')}else if(r.phase==='between'){r.timeLeft-=dt;if(r.timeLeft<=0){if(r.round>=MAX_ROUNDS){r.matchDone=true;startVote(r)}else startRound(r)}}botAI(r,dt);emit(r)}},TICK);
server.listen(PORT,()=>console.log('Dropz Prop Hunt running on '+PORT));
